export enum Events {
  AddPlayerToNamespace = "AddPlayerToNamespace",
  BroadcastNamespaced = "BroadcastNamespaced",
  ServerToPlayer = "ServerToPlayer",
  MatchUpdated = "MatchUpdated",
  MatchEnded = "MatchEnded",
  GameServerStatus = "GameServerStatus",
  GameList = "GameList",
  LobbyCreate = "LobbyCreate",
  LobbyJoin = "LobbyJoin",
  LobbyTournamentStart = "LobbyTournamentStart",
  LobbyTournamentContinue = "LobbyTournamentContinue",
  LobbyPlayerBan = "LobbyPlayerBan",
  LobbyPlayerKick = "LobbyPlayerKick",
  PlayerDisconnected = "PlayerDisconnected",
}
