export const CONNECT = 'SERVER_CONNECT';
export const DISCONNECT = 'SERVER_DISCONNECT';
export const CONNECTED = 'SERVER_CONNECTED';
export const DISCONNECTED = 'SERVER_DISCONNECTED';
export const CONNECTION_ERROR = 'SERVER_CONNECTION_ERROR';